### ISSUE TITLE
Error with Callback

### ISSUE THREAD

**Issue by PeregrineSpur** [UnaBiz/sigfox-gcloud#1]
Setup Google cloud as per instructions. Getting error on callback.

{
 textPayload:  "TypeError: Cannot read property 'data' of undefined
    at main (/user_code/index.js:218:52)
    at /var/tmp/worker/worker.js:638:7
    at /var/tmp/worker/worker.js:622:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)"   
 insertId:  "000000-f648eeea-22bb-46b0-9b7e-95931cebe47b"   
 resource: {
  type:  "cloud_function"    
  labels: {
   function_name:  "sigfoxCallback"     
   project_id:  "zettabyt-iot"     
   region:  "us-central1"     
  }
 }
 timestamp:  "2017-06-11T15:16:04.352Z"   
 severity:  "ERROR"   
 labels: {
  execution_id:  "p4fpeuwm31oq"    
 }
 logName:  "projects/zettabyt-iot/logs/cloudfunctions.googleapis.com%2Fcloud-functions"   
 receiveTimestamp:  "2017-06-11T15:16:10.288159464Z"   
}

Assistance in this regard would be appreciated.

**Comment by lupyuen-unabiz** [comment]
Hi: Thanks for trying this out - and also bearing with the initial bugs :-)

The message suggests that the "data" field is missing from the callback or maybe it was configured with the incorrect content type.

(1) Can you confirm that the Sigfox callback is set to have content type "application/json"?

(2) Do you have other logs in Google Cloud Logging to show the message received from the Sigfox callback?

Thanks.

**Comment by lupyuen-unabiz** [comment]
Also could you confirm the SIgfox callback settings:

  -  **Type**: <br>
        **`DATA, BIDIR`**
    
    -  **Channel**: <br>
        **`URL`**
    
    -  **Send duplicate**: <br>
        **Checked (Yes)**
    
    -  **Custom payload config**: <br>
        **(Blank)**
    
    -  **URL Pattern**: <br>
        Enter the **Sigfox Callback URL**
        It should look like:   
        `https://us-central1-myproject.cloudfunctions.net/sigfoxCallback`          

    -  **Use HTTP Method**: <br>
        **`POST`**
        
    -  **Send SNI**: <br>
        **Checked (Yes)**

    -  **Headers**: <br>
        **(Blank)**

    -  **Content Type**: <br>
        **`application/json`**
            
    - Set the **Body** (Sigfox message payload) as:

        ```json
        {                             
         "device" : "{device}",        
         "data" : "{data}",            
         "time" : "{time}",            
         "duplicate": "{duplicate}",   
         "snr": "{snr}",               
         "station": "{station}",       
         "avgSnr": "{avgSnr}",         
         "lat": "{lat}",               
         "lng": "{lng}",               
         "rssi": "{rssi}",             
         "seqNumber": "{seqNumber}",   
         "ack": "{ack}",               
         "longPolling": "{longPolling}"
        }                             
        ```

**Comment by PeregrineSpur** [comment]
Hi,

Happy to help iron out the bugs.:) While we were waiting for a response we thought we would try it with the AWS iot service which worked to a certain degree. 

We are getting messages through but  have not been able to decode them properly. I don't quite understand the hex decoding as it does not seem to be straight forward hex? We changed the code on the arduino to send strings which does give us proper hex. 

Anyhow your installation guide is really good. But it may be missing a step somewhere? The google backend does not seem to see the message at all. 


Thanks & Regards 
Perry Spurway

On 13 Jun 2017, at 05:01, Lee Lup Yuen <notifications@github.com> wrote:

Hi: Thanks for trying this out - and also bearing with the initial bugs :-)

The message suggests that the "data" field is missing from the callback or maybe it was configured with the incorrect content type.

(1) Can you confirm that the Sigfox callback is set to have content type "application/json"?

(2) Do you have other logs in Google Cloud Logging to show the message received from the Sigfox callback?

Thanks.

**Comment by lupyuen-unabiz** [comment]
Hi Perry: Could you do one quick check - in the Sigfox backend you can click on your device and see the list messages.  Look under the "callback" column.  Do you see any errors like this?

![image](https://user-images.githubusercontent.com/20881097/27069452-62684704-5047-11e7-88a6-acd6828b26f7.png)

The correct response should look like this:

![image](https://user-images.githubusercontent.com/20881097/27069472-7b969f82-5047-11e7-9c26-9f3a7584edbd.png)

**Comment by PeregrineSpur** [comment]
Hi, This is what we were getting

**Comment by PeregrineSpur** [comment]
Hi,
We are going to do a fresh install following the guide to make sure we have not missed anything on our side.

Thanks

**Comment by PeregrineSpur** [comment]
One more thing, are you running on windows? As we had to update the ./ to full file paths to get the scripts to run

Would you be able to send me a number so we can communicate over WhatsApp?

**Comment by PeregrineSpur** [comment]
In step 2 we need some clarification please. 

“
Open a bash command prompt. For Windows, open "Bash on Ubuntu on Windows."
Create a file named .env in the sigfox-gcloud folder
and populate the GCLOUD_PROJECT variable with your project ID like this (change myproject to your project ID):

echo GCLOUD_PROJECT=myproject >.env
Firstly we are working on MAC, so bash is similar to linux but not identical. 
"Create a file named .env”  what must the filename be with extension '.env’? 

Thanks

**Comment by lupyuen-unabiz** [comment]
> One more thing, are you running on windows? As we had to update the ./ to full file paths to get the scripts to run

Sorry I didn't package the scripts correctly - I'm developing on both Mac and Windows with Ubuntu.  The scripts need to be run in the root directory of sigfox-gcloud, i.e.
```
git clone https://github.com/UnaBiz/sigfox-gcloud.git
cd sigfox-gcloud
## Run scripts here. You may need to chmod, e.g.
chmod +x scripts/*.sh
scripts/deployall.sh 
```

**Comment by lupyuen-unabiz** [comment]
`.env` is a trick I have learned recently - it comes from https://www.npmjs.com/package/dotenv

Reason for doing this is that you could put all your system credentials into the `.env` file, and your app will be able to read the variables as though they are defined as shell variables, i.e. `process.env.varname`

Maybe when I have some time I'll create a screencast of the entire installation process?  It only takes a few mins to finish the installation - but maybe there's a chance that I have missed out some steps

**Comment by PeregrineSpur** [comment]
Hi Lee, we did a complete reinstall and still getting the same problem. Maybe if you can do an install following your instructions line by line, maybe we can identify the error

Regards 
Perry Spurway

On 14 Jun 2017, at 09:53, Lee Lup Yuen <notifications@github.com> wrote:

.env is a trick I have learned recently - it comes from https://www.npmjs.com/package/dotenv

Reason for doing this is that you could put all your system credentials into the .env file, and your app will be able to read the variables as though they are defined as shell variables, i.e. process.env.varname

Maybe when I have some time I'll create a screencast of the entire installation process? It only takes a few mins to finish the installation - but maybe there's a chance that I have missed out some steps
